image: maven:3-amazoncorretto-17

build:
    before_script:
        - "echo \"<settings><servers><server><id>net.hep.ami-releases</id><username>${AMI_MAVEN_REPO_USERNAME}</username><password>${AMI_MAVEN_REPO_PASSWORD}</password></server></servers></settings>\" > ~/.m2/settings.xml"
    script:
        - "sed \"s/{{CURRENT_YEAR}}/$(date +%Y)/g\" /tools/awf_stub.py > ./tools/awf.py"
        - "mvn deploy:deploy-file -DgroupId=net.hep.ami -DartifactId=AWF -Dversion=1.0.0 -Dfile=./tools/awf.py -Dpackaging=py -DgeneratePom=true -DrepositoryId=net.hep.ami-releases -Durl=https://repo.ami-ecosystem.in2p3.fr/releases"
