/*
 * AMI Web Framework - AMICommand.js
 *
 * Copyright (c) 2014-{{CURRENT_YEAR}} The AMI Team / LPSC / IN2P3
 *
 * This file must be used under the terms of the CeCILL-C:
 * http://www.cecill.info/licences/Licence_CeCILL-C_V1-en.html
 * http://www.cecill.info/licences/Licence_CeCILL-C_V1-fr.html
 *
 */

'use strict';

import HttpClient from 'ami-http-client';
import MqttClient from 'ami-mqtt-client';

/*--------------------------------------------------------------------------------------------------------------------*/
/* amiCommand                                                                                                         */
/*--------------------------------------------------------------------------------------------------------------------*/

/**
 * The AMI command subsystem
 */

class AMICommand {
	#httpClient = null;
	#mqttClient = null;

	static init(httpEndpoint, mqttEndpoint)
	{
		this.#httpClient = new HttpClient(httpEndpoint);
		this.#mqttClient = new MqttClient(mqttEndpoint);
	}

	/**
	 * Executes an AMI command
	 * @param {String} command the command
	 * @param {Object} [options] dictionary of optional parameters (mqtt, endpoint, serverName, converter, extras, params, context, timeout)
	 * @returns {$.Deferred} A JQuery deferred object
	 */
	static execute(command, options)
	{
		if(typeof options !== 'undefined' && options.mqtt) {
			return this.#mqttClient.execute(command, options);
		} else {
			return this.#httpClient.execute(command, options);
		}
	 }

	/**
	 * Sign in by JWT token
	 * @param {String} token the password
	 * @param {String} serverName the server name
	 * @returns {$.Deferred} A JQuery deferred object
	 */
	 static signInByToken(token, serverName)
	 {
	 	return this.#mqttClient.signInByToken(token, serverName);
	 }


	/**
	 * Logs in by login/password
	 * @param {String} user the user
	 * @param {String} pass the password
	 * @param {Object} [settings] dictionary of settings (context)
	 * @returns {$.Deferred} A JQuery deferred object
	 */
	static passLogin(user, pass, settings) {
		this.#httpClient.signInByPassword(user, pass, settings);
	}

	/**
	 * Logs in by certificate
	 * @param {Object} [settings] dictionary of settings (context)
	 * @returns {$.Deferred} A JQuery deferred object
	 */
	static certLogin = settings => this.#httpClient.signInByCertificate(settings);

	/**
	 * Logs out
	 * @param {Object} [settings] dictionary of settings (context)
	 * @returns {$.Deferred} A JQuery deferred object
	 */
	static signOut = settings => this.#httpClient.signOut(settings);

	/**
	 * Attaches a certificate
	 * @param {String} user the user
	 * @param {String} pass the password
	 * @param {Object} [settings] dictionary of settings (context)
	 * @returns {$.Deferred} A JQuery deferred object
	 */
	static attachCert = (user, pass, settings) => {
		return this.execute('GetSessionInfo -attachCert -amiLogin="' + amiWebApp.textToString(user) + '" -amiPassword="' + amiWebApp.textToString(pass) + '"', settings);
	}

	/**
	 * Detaches a certificate
	 * @param {String} user the user
	 * @param {String} pass the password
	 * @param {Object} [settings] dictionary of settings (context)
	 * @returns {$.Deferred} A JQuery deferred object
	 */

	static detachCert(user, pass, settings)
	{
		return this.execute('GetSessionInfo -detachCert -amiLogin="' + amiWebApp.textToString(user) + '" -amiPassword="' + amiWebApp.textToString(pass) + '"', settings);
	}

	/**
	 * Adds a new user
	 * @param {String} user the user
	 * @param {String} pass the password
	 * @param {String} firstName the first name
	 * @param {String} lastName the last name
	 * @param {String} email the email
	 * @param {String} captchaHash the captcha hash generated by AMI
	 * @param {String} captchaText the captcha text entered by the user
	 * @param {Boolean} attachCert attach the current certificate
	 * @param {Boolean} agree agree with the terms and conditions
	 * @param {Object} [settings] dictionary of settings (context)
	 * @returns {$.Deferred} A JQuery deferred object
	 */

	static addUser = (user, pass, firstName, lastName, email, captchaHash, captchaText, attachCert, agree, settings) => {
		return this.execute('AddUser -amiLogin="' + amiWebApp.textToString(user) + '" -amiPassword="' + amiWebApp.textToString(pass) + '" -firstName="' + amiWebApp.textToString(firstName) + '" -lastName="' + amiWebApp.textToString(lastName) + '" -email="' + amiWebApp.textToString(email) + '" -captchaHash="' + amiWebApp.textToString(captchaHash) + '" -captchaText="' + amiWebApp.textToString(captchaText) + '" ' + (attachCert ? ' -attachCert' : '') + (agree ? ' -agree' : ''), settings);
	}

	/**
	 * Changes the account information
	 * @param {String} firstName the first name
	 * @param {String} lastName the last name
	 * @param {String} email the email
	 * @param {Object} [settings] dictionary of settings (context)
	 * @returns {$.Deferred} A JQuery deferred object
	 */

	static changeInfo = (firstName, lastName, email, settings) => {
		return this.execute('SetUserInfo -firstName="' + amiWebApp.textToString(firstName) + '" -lastName="' + amiWebApp.textToString(lastName) + '" -email="' + amiWebApp.textToString(email) + '"', settings);
	}

	/**
	 * Changes the account password
	 * @param {String} user the user
	 * @param {String} oldPass the old password
	 * @param {String} newPass the new password
	 * @param {Object} [settings] dictionary of settings (context)
	 * @returns {$.Deferred} A JQuery deferred object
	 */

	static changePass = (user, oldPass, newPass, settings) => {
		return this.execute('ChangePassword -amiLogin="' + amiWebApp.textToString(user) + '" -amiPasswordOld="' + amiWebApp.textToString(oldPass) + '" -amiPasswordNew="' + amiWebApp.textToString(newPass) + '"', settings);
	}

	/**
	 * Resets the account password
	 * @param {String} user the user
	 * @param {String} captchaHash the captcha hash generated by AMI
	 * @param {String} captchaText the captcha text entered by the user
	 * @param {Object} [settings] dictionary of settings (context)
	 * @returns {$.Deferred} A JQuery deferred object
	 */

	static resetPass = (user, captchaHash, captchaText, settings) => {
		return this.execute('ResetPassword -amiLogin="' + amiWebApp.textToString(user) + '" -captchaHash="' + amiWebApp.textToString(captchaHash) + '" -captchaText="' + amiWebApp.textToString(captchaText) + '"', settings);
	}
}

const amiCommand = new AMICommand();
export default amiCommand;

if(typeof window !== 'undefined') {
	window.amiCommand = amiCommand;
}